### ISSUE TITLE
Smart-amplifiers missing in max98373/max98927 topology

### ISSUE THREAD

**Issue by coolstar** [thesofproject/avs-topology-xml#2]
These 2 devices seem to be smart amps that need a special topology to work. Can one be provided for these?

**Comment by cujomalainey** [comment]
> These 2 devices seem to be smart amps that need a special topology to work. Can one be provided for these?

@ryans-lee I am not sure what your plan is for the DSM in the Linux world

**Comment by crojewsk-intel** [comment]
@coolstar Not everything can be shared. Unfortunately, cannot comment on usage of some of the 3rd party modules outside of supported set of configurations.

What we can do is provide a base-firmware-based workaround i.e.: a Peakvol instead of DSM.

**Comment by coolstar** [comment]
@crojewsk-intel figured as much; in that time I've already figured out how to get it working in my own driver with IPC messages dumped from the legacy skylake driver (combined with module extracted from CrOS), so don't need the topologies anymore

**Comment by crojewsk-intel** [comment]
Your description is very vague, it's hard to grasp what exactly you are talking about.

Note: some payloads sent to the 3rd party modules are tailored for specific configuration. applying them in generic fashion may lead to unexpected behavior.

FYI:
- peakvol support has been provided in avsdk with [avstplg: Add volume kcontrol support](https://github.com/thesofproject/avsdk/pull/2)
- example of usage has been provided in avs-topology-xml with [dmic: Update topology to expose volume control](https://github.com/thesofproject/avs-topology-xml/pull/3)

Closing as parts of the request are N/A and the proposed workaround has been provided.

**Comment by crojewsk-intel** [comment]
Reference topologies for max98373 and max98927 devices with 3rd party smart-amplifier replaced by PeakVolume module have been provided with #14 and #15 respectively.
